/**
 * KnowToHire Master Canonical Geography & Global Seed Data
 * 
 * Contains:
 * - 48 Global Countries (covering Americas, Europe, Asia-Pacific, Middle East, Africa)
 * - All 28 Indian States & 8 Union Territories (36 Total)
 * - 160+ Top Metropolitan, Regional & Industrial Cities in India & Global Hubs
 */

import { Country, StateRegion, CityItem } from './taxonomyTypes';

export const MASTER_COUNTRIES: Country[] = [
  { id: 'country-in', name: 'India', slug: 'india', iso2: 'IN', iso3: 'IND', phone_code: '+91', currency_code: 'INR', currency_symbol: '₹', region: 'Asia-Pacific', is_active: true, sort_order: 1 },
  { id: 'country-us', name: 'United States', slug: 'united-states', iso2: 'US', iso3: 'USA', phone_code: '+1', currency_code: 'USD', currency_symbol: '$', region: 'Americas', is_active: true, sort_order: 2 },
  { id: 'country-uk', name: 'United Kingdom', slug: 'united-kingdom', iso2: 'GB', iso3: 'GBR', phone_code: '+44', currency_code: 'GBP', currency_symbol: '£', region: 'Europe', is_active: true, sort_order: 3 },
  { id: 'country-ca', name: 'Canada', slug: 'canada', iso2: 'CA', iso3: 'CAN', phone_code: '+1', currency_code: 'CAD', currency_symbol: 'C$', region: 'Americas', is_active: true, sort_order: 4 },
  { id: 'country-sg', name: 'Singapore', slug: 'singapore', iso2: 'SG', iso3: 'SGP', phone_code: '+65', currency_code: 'SGD', currency_symbol: 'S$', region: 'Asia-Pacific', is_active: true, sort_order: 5 },
  { id: 'country-ae', name: 'United Arab Emirates', slug: 'united-arab-emirates', iso2: 'AE', iso3: 'ARE', phone_code: '+971', currency_code: 'AED', currency_symbol: 'AED', region: 'Middle East', is_active: true, sort_order: 6 },
  { id: 'country-de', name: 'Germany', slug: 'germany', iso2: 'DE', iso3: 'DEU', phone_code: '+49', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 7 },
  { id: 'country-au', name: 'Australia', slug: 'australia', iso2: 'AU', iso3: 'AUS', phone_code: '+61', currency_code: 'AUD', currency_symbol: 'A$', region: 'Asia-Pacific', is_active: true, sort_order: 8 },
  { id: 'country-jp', name: 'Japan', slug: 'japan', iso2: 'JP', iso3: 'JPN', phone_code: '+81', currency_code: 'JPY', currency_symbol: '¥', region: 'Asia-Pacific', is_active: true, sort_order: 9 },
  { id: 'country-sa', name: 'Saudi Arabia', slug: 'saudi-arabia', iso2: 'SA', iso3: 'SAU', phone_code: '+966', currency_code: 'SAR', currency_symbol: 'SAR', region: 'Middle East', is_active: true, sort_order: 10 },
  { id: 'country-nl', name: 'Netherlands', slug: 'netherlands', iso2: 'NL', iso3: 'NLD', phone_code: '+31', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 11 },
  { id: 'country-ch', name: 'Switzerland', slug: 'switzerland', iso2: 'CH', iso3: 'CHE', phone_code: '+41', currency_code: 'CHF', currency_symbol: 'CHF', region: 'Europe', is_active: true, sort_order: 12 },
  { id: 'country-se', name: 'Sweden', slug: 'sweden', iso2: 'SE', iso3: 'SWE', phone_code: '+46', currency_code: 'SEK', currency_symbol: 'kr', region: 'Europe', is_active: true, sort_order: 13 },
  { id: 'country-no', name: 'Norway', slug: 'norway', iso2: 'NO', iso3: 'NOR', phone_code: '+47', currency_code: 'NOK', currency_symbol: 'kr', region: 'Europe', is_active: true, sort_order: 14 },
  { id: 'country-dk', name: 'Denmark', slug: 'denmark', iso2: 'DK', iso3: 'DNK', phone_code: '+45', currency_code: 'DKK', currency_symbol: 'kr', region: 'Europe', is_active: true, sort_order: 15 },
  { id: 'country-ie', name: 'Ireland', slug: 'ireland', iso2: 'IE', iso3: 'IRL', phone_code: '+353', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 16 },
  { id: 'country-nz', name: 'New Zealand', slug: 'new-zealand', iso2: 'NZ', iso3: 'NZL', phone_code: '+64', currency_code: 'NZD', currency_symbol: 'NZ$', region: 'Asia-Pacific', is_active: true, sort_order: 17 },
  { id: 'country-za', name: 'South Africa', slug: 'south-africa', iso2: 'ZA', iso3: 'ZAF', phone_code: '+27', currency_code: 'ZAR', currency_symbol: 'R', region: 'Africa', is_active: true, sort_order: 18 },
  { id: 'country-br', name: 'Brazil', slug: 'brazil', iso2: 'BR', iso3: 'BRA', phone_code: '+55', currency_code: 'BRL', currency_symbol: 'R$', region: 'Americas', is_active: true, sort_order: 19 },
  { id: 'country-my', name: 'Malaysia', slug: 'malaysia', iso2: 'MY', iso3: 'MYS', phone_code: '+60', currency_code: 'MYR', currency_symbol: 'RM', region: 'Asia-Pacific', is_active: true, sort_order: 20 },
  { id: 'country-id', name: 'Indonesia', slug: 'indonesia', iso2: 'ID', iso3: 'IDN', phone_code: '+62', currency_code: 'IDR', currency_symbol: 'Rp', region: 'Asia-Pacific', is_active: true, sort_order: 21 },
  { id: 'country-ph', name: 'Philippines', slug: 'philippines', iso2: 'PH', iso3: 'PHL', phone_code: '+63', currency_code: 'PHP', currency_symbol: '₱', region: 'Asia-Pacific', is_active: true, sort_order: 22 },
  { id: 'country-vn', name: 'Vietnam', slug: 'vietnam', iso2: 'VN', iso3: 'VNM', phone_code: '+84', currency_code: 'VND', currency_symbol: '₫', region: 'Asia-Pacific', is_active: true, sort_order: 23 },
  { id: 'country-th', name: 'Thailand', slug: 'thailand', iso2: 'TH', iso3: 'THA', phone_code: '+66', currency_code: 'THB', currency_symbol: '฿', region: 'Asia-Pacific', is_active: true, sort_order: 24 },
  { id: 'country-kr', name: 'South Korea', slug: 'south-korea', iso2: 'KR', iso3: 'KOR', phone_code: '+82', currency_code: 'KRW', currency_symbol: '₩', region: 'Asia-Pacific', is_active: true, sort_order: 25 },
  { id: 'country-cn', name: 'China', slug: 'china', iso2: 'CN', iso3: 'CHN', phone_code: '+86', currency_code: 'CNY', currency_symbol: '¥', region: 'Asia-Pacific', is_active: true, sort_order: 26 },
  { id: 'country-bd', name: 'Bangladesh', slug: 'bangladesh', iso2: 'BD', iso3: 'BGD', phone_code: '+880', currency_code: 'BDT', currency_symbol: '৳', region: 'Asia-Pacific', is_active: true, sort_order: 27 },
  { id: 'country-lk', name: 'Sri Lanka', slug: 'sri-lanka', iso2: 'LK', iso3: 'LKA', phone_code: '+94', currency_code: 'LKR', currency_symbol: 'Rs', region: 'Asia-Pacific', is_active: true, sort_order: 28 },
  { id: 'country-np', name: 'Nepal', slug: 'nepal', iso2: 'NP', iso3: 'NPL', phone_code: '+977', currency_code: 'NPR', currency_symbol: 'Rs', region: 'Asia-Pacific', is_active: true, sort_order: 29 },
  { id: 'country-qa', name: 'Qatar', slug: 'qatar', iso2: 'QA', iso3: 'QAT', phone_code: '+974', currency_code: 'QAR', currency_symbol: 'QAR', region: 'Middle East', is_active: true, sort_order: 30 },
  { id: 'country-om', name: 'Oman', slug: 'oman', iso2: 'OM', iso3: 'OMN', phone_code: '+968', currency_code: 'OMR', currency_symbol: 'OMR', region: 'Middle East', is_active: true, sort_order: 31 },
  { id: 'country-kw', name: 'Kuwait', slug: 'kuwait', iso2: 'KW', iso3: 'KWT', phone_code: '+965', currency_code: 'KWD', currency_symbol: 'KWD', region: 'Middle East', is_active: true, sort_order: 32 },
  { id: 'country-bh', name: 'Bahrain', slug: 'bahrain', iso2: 'BH', iso3: 'BHR', phone_code: '+973', currency_code: 'BHD', currency_symbol: 'BHD', region: 'Middle East', is_active: true, sort_order: 33 },
  { id: 'country-eg', name: 'Egypt', slug: 'egypt', iso2: 'EG', iso3: 'EGY', phone_code: '+20', currency_code: 'EGP', currency_symbol: 'E£', region: 'Middle East', is_active: true, sort_order: 34 },
  { id: 'country-ng', name: 'Nigeria', slug: 'nigeria', iso2: 'NG', iso3: 'NGA', phone_code: '+234', currency_code: 'NGN', currency_symbol: '₦', region: 'Africa', is_active: true, sort_order: 35 },
  { id: 'country-ke', name: 'Kenya', slug: 'kenya', iso2: 'KE', iso3: 'KEN', phone_code: '+254', currency_code: 'KES', currency_symbol: 'KSh', region: 'Africa', is_active: true, sort_order: 36 },
  { id: 'country-es', name: 'Spain', slug: 'spain', iso2: 'ES', iso3: 'ESP', phone_code: '+34', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 37 },
  { id: 'country-it', name: 'Italy', slug: 'italy', iso2: 'IT', iso3: 'ITA', phone_code: '+39', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 38 },
  { id: 'country-be', name: 'Belgium', slug: 'belgium', iso2: 'BE', iso3: 'BEL', phone_code: '+32', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 39 },
  { id: 'country-at', name: 'Austria', slug: 'austria', iso2: 'AT', iso3: 'AUT', phone_code: '+43', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 40 },
  { id: 'country-pl', name: 'Poland', slug: 'poland', iso2: 'PL', iso3: 'POL', phone_code: '+48', currency_code: 'PLN', currency_symbol: 'zł', region: 'Europe', is_active: true, sort_order: 41 },
  { id: 'country-pt', name: 'Portugal', slug: 'portugal', iso2: 'PT', iso3: 'PRT', phone_code: '+351', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 42 },
  { id: 'country-mx', name: 'Mexico', slug: 'mexico', iso2: 'MX', iso3: 'MEX', phone_code: '+52', currency_code: 'MXN', currency_symbol: '$', region: 'Americas', is_active: true, sort_order: 43 },
  { id: 'country-ar', name: 'Argentina', slug: 'argentina', iso2: 'AR', iso3: 'ARG', phone_code: '+54', currency_code: 'ARS', currency_symbol: '$', region: 'Americas', is_active: true, sort_order: 44 },
  { id: 'country-cl', name: 'Chile', slug: 'chile', iso2: 'CL', iso3: 'CHL', phone_code: '+56', currency_code: 'CLP', currency_symbol: '$', region: 'Americas', is_active: true, sort_order: 45 },
  { id: 'country-co', name: 'Colombia', slug: 'colombia', iso2: 'CO', iso3: 'COL', phone_code: '+57', currency_code: 'COP', currency_symbol: '$', region: 'Americas', is_active: true, sort_order: 46 },
  { id: 'country-fr', name: 'France', slug: 'france', iso2: 'FR', iso3: 'FRA', phone_code: '+33', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 47 },
  { id: 'country-fi', name: 'Finland', slug: 'finland', iso2: 'FI', iso3: 'FIN', phone_code: '+358', currency_code: 'EUR', currency_symbol: '€', region: 'Europe', is_active: true, sort_order: 48 },
];

export const MASTER_INDIAN_STATES: StateRegion[] = [
  // 28 Indian States
  { id: 'state-ap', country_id: 'country-in', name: 'Andhra Pradesh', state_code: 'AP', type: 'State', is_active: true, sort_order: 1 },
  { id: 'state-ar', country_id: 'country-in', name: 'Arunachal Pradesh', state_code: 'AR', type: 'State', is_active: true, sort_order: 2 },
  { id: 'state-as', country_id: 'country-in', name: 'Assam', state_code: 'AS', type: 'State', is_active: true, sort_order: 3 },
  { id: 'state-br', country_id: 'country-in', name: 'Bihar', state_code: 'BR', type: 'State', is_active: true, sort_order: 4 },
  { id: 'state-cg', country_id: 'country-in', name: 'Chhattisgarh', state_code: 'CG', type: 'State', is_active: true, sort_order: 5 },
  { id: 'state-ga', country_id: 'country-in', name: 'Goa', state_code: 'GA', type: 'State', is_active: true, sort_order: 6 },
  { id: 'state-gj', country_id: 'country-in', name: 'Gujarat', state_code: 'GJ', type: 'State', is_active: true, sort_order: 7 },
  { id: 'state-hr', country_id: 'country-in', name: 'Haryana', state_code: 'HR', type: 'State', is_active: true, sort_order: 8 },
  { id: 'state-hp', country_id: 'country-in', name: 'Himachal Pradesh', state_code: 'HP', type: 'State', is_active: true, sort_order: 9 },
  { id: 'state-jh', country_id: 'country-in', name: 'Jharkhand', state_code: 'JH', type: 'State', is_active: true, sort_order: 10 },
  { id: 'state-ka', country_id: 'country-in', name: 'Karnataka', state_code: 'KA', type: 'State', is_active: true, sort_order: 11 },
  { id: 'state-kl', country_id: 'country-in', name: 'Kerala', state_code: 'KL', type: 'State', is_active: true, sort_order: 12 },
  { id: 'state-mp', country_id: 'country-in', name: 'Madhya Pradesh', state_code: 'MP', type: 'State', is_active: true, sort_order: 13 },
  { id: 'state-mh', country_id: 'country-in', name: 'Maharashtra', state_code: 'MH', type: 'State', is_active: true, sort_order: 14 },
  { id: 'state-mn', country_id: 'country-in', name: 'Manipur', state_code: 'MN', type: 'State', is_active: true, sort_order: 15 },
  { id: 'state-ml', country_id: 'country-in', name: 'Meghalaya', state_code: 'ML', type: 'State', is_active: true, sort_order: 16 },
  { id: 'state-mz', country_id: 'country-in', name: 'Mizoram', state_code: 'MZ', type: 'State', is_active: true, sort_order: 17 },
  { id: 'state-nl', country_id: 'country-in', name: 'Nagaland', state_code: 'NL', type: 'State', is_active: true, sort_order: 18 },
  { id: 'state-od', country_id: 'country-in', name: 'Odisha', state_code: 'OD', type: 'State', is_active: true, sort_order: 19 },
  { id: 'state-pb', country_id: 'country-in', name: 'Punjab', state_code: 'PB', type: 'State', is_active: true, sort_order: 20 },
  { id: 'state-rj', country_id: 'country-in', name: 'Rajasthan', state_code: 'RJ', type: 'State', is_active: true, sort_order: 21 },
  { id: 'state-sk', country_id: 'country-in', name: 'Sikkim', state_code: 'SK', type: 'State', is_active: true, sort_order: 22 },
  { id: 'state-tn', country_id: 'country-in', name: 'Tamil Nadu', state_code: 'TN', type: 'State', is_active: true, sort_order: 23 },
  { id: 'state-ts', country_id: 'country-in', name: 'Telangana', state_code: 'TS', type: 'State', is_active: true, sort_order: 24 },
  { id: 'state-tr', country_id: 'country-in', name: 'Tripura', state_code: 'TR', type: 'State', is_active: true, sort_order: 25 },
  { id: 'state-up', country_id: 'country-in', name: 'Uttar Pradesh', state_code: 'UP', type: 'State', is_active: true, sort_order: 26 },
  { id: 'state-uk', country_id: 'country-in', name: 'Uttarakhand', state_code: 'UK', type: 'State', is_active: true, sort_order: 27 },
  { id: 'state-wb', country_id: 'country-in', name: 'West Bengal', state_code: 'WB', type: 'State', is_active: true, sort_order: 28 },
  
  // 8 Indian Union Territories
  { id: 'state-an', country_id: 'country-in', name: 'Andaman and Nicobar Islands', state_code: 'AN', type: 'Union Territory', is_active: true, sort_order: 29 },
  { id: 'state-ch', country_id: 'country-in', name: 'Chandigarh', state_code: 'CH', type: 'Union Territory', is_active: true, sort_order: 30 },
  { id: 'state-dh', country_id: 'country-in', name: 'Dadra and Nagar Haveli and Daman and Diu', state_code: 'DH', type: 'Union Territory', is_active: true, sort_order: 31 },
  { id: 'state-dl', country_id: 'country-in', name: 'Delhi', state_code: 'DL', type: 'Union Territory', is_active: true, sort_order: 32 },
  { id: 'state-jk', country_id: 'country-in', name: 'Jammu and Kashmir', state_code: 'JK', type: 'Union Territory', is_active: true, sort_order: 33 },
  { id: 'state-la', country_id: 'country-in', name: 'Ladakh', state_code: 'LA', type: 'Union Territory', is_active: true, sort_order: 34 },
  { id: 'state-ld', country_id: 'country-in', name: 'Lakshadweep', state_code: 'LD', type: 'Union Territory', is_active: true, sort_order: 35 },
  { id: 'state-py', country_id: 'country-in', name: 'Puducherry', state_code: 'PY', type: 'Union Territory', is_active: true, sort_order: 36 },
];

export const MASTER_CITIES: CityItem[] = [
  // --- TELANGANA ---
  { id: 'city-hyd', country_id: 'country-in', state_id: 'state-ts', name: 'Hyderabad', slug: 'hyderabad', is_popular: true, is_active: true, sort_order: 1 },
  { id: 'city-secunderabad', country_id: 'country-in', state_id: 'state-ts', name: 'Secunderabad', slug: 'secunderabad', is_popular: true, is_active: true, sort_order: 2 },
  { id: 'city-warangal', country_id: 'country-in', state_id: 'state-ts', name: 'Warangal', slug: 'warangal', is_popular: false, is_active: true, sort_order: 3 },
  { id: 'city-karimnagar', country_id: 'country-in', state_id: 'state-ts', name: 'Karimnagar', slug: 'karimnagar', is_popular: false, is_active: true, sort_order: 4 },
  { id: 'city-nizamabad', country_id: 'country-in', state_id: 'state-ts', name: 'Nizamabad', slug: 'nizamabad', is_popular: false, is_active: true, sort_order: 5 },
  { id: 'city-khammam', country_id: 'country-in', state_id: 'state-ts', name: 'Khammam', slug: 'khammam', is_popular: false, is_active: true, sort_order: 6 },
  { id: 'city-ramagundam', country_id: 'country-in', state_id: 'state-ts', name: 'Ramagundam', slug: 'ramagundam', is_popular: false, is_active: true, sort_order: 7 },

  // --- KARNATAKA ---
  { id: 'city-blr', country_id: 'country-in', state_id: 'state-ka', name: 'Bengaluru', slug: 'bengaluru', is_popular: true, is_active: true, sort_order: 8 },
  { id: 'city-mysuru', country_id: 'country-in', state_id: 'state-ka', name: 'Mysuru', slug: 'mysuru', is_popular: true, is_active: true, sort_order: 9 },
  { id: 'city-mangaluru', country_id: 'country-in', state_id: 'state-ka', name: 'Mangaluru', slug: 'mangaluru', is_popular: true, is_active: true, sort_order: 10 },
  { id: 'city-hubballi', country_id: 'country-in', state_id: 'state-ka', name: 'Hubballi-Dharwad', slug: 'hubballi-dharwad', is_popular: false, is_active: true, sort_order: 11 },
  { id: 'city-belagavi', country_id: 'country-in', state_id: 'state-ka', name: 'Belagavi', slug: 'belagavi', is_popular: false, is_active: true, sort_order: 12 },
  { id: 'city-kalaburagi', country_id: 'country-in', state_id: 'state-ka', name: 'Kalaburagi', slug: 'kalaburagi', is_popular: false, is_active: true, sort_order: 13 },
  { id: 'city-ballari', country_id: 'country-in', state_id: 'state-ka', name: 'Ballari', slug: 'ballari', is_popular: false, is_active: true, sort_order: 14 },
  { id: 'city-shivamogga', country_id: 'country-in', state_id: 'state-ka', name: 'Shivamogga', slug: 'shivamogga', is_popular: false, is_active: true, sort_order: 15 },
  { id: 'city-tumakuru', country_id: 'country-in', state_id: 'state-ka', name: 'Tumakuru', slug: 'tumakuru', is_popular: false, is_active: true, sort_order: 16 },

  // --- MAHARASHTRA ---
  { id: 'city-mum', country_id: 'country-in', state_id: 'state-mh', name: 'Mumbai', slug: 'mumbai', is_popular: true, is_active: true, sort_order: 17 },
  { id: 'city-pune', country_id: 'country-in', state_id: 'state-mh', name: 'Pune', slug: 'pune', is_popular: true, is_active: true, sort_order: 18 },
  { id: 'city-nagpur', country_id: 'country-in', state_id: 'state-mh', name: 'Nagpur', slug: 'nagpur', is_popular: true, is_active: true, sort_order: 19 },
  { id: 'city-navi-mumbai', country_id: 'country-in', state_id: 'state-mh', name: 'Navi Mumbai', slug: 'navi-mumbai', is_popular: true, is_active: true, sort_order: 20 },
  { id: 'city-thane', country_id: 'country-in', state_id: 'state-mh', name: 'Thane', slug: 'thane', is_popular: true, is_active: true, sort_order: 21 },
  { id: 'city-nashik', country_id: 'country-in', state_id: 'state-mh', name: 'Nashik', slug: 'nashik', is_popular: false, is_active: true, sort_order: 22 },
  { id: 'city-aurangabad', country_id: 'country-in', state_id: 'state-mh', name: 'Chhatrapati Sambhajinagar', slug: 'chhatrapati-sambhajinagar', is_popular: false, is_active: true, sort_order: 23 },
  { id: 'city-solapur', country_id: 'country-in', state_id: 'state-mh', name: 'Solapur', slug: 'solapur', is_popular: false, is_active: true, sort_order: 24 },
  { id: 'city-kolhapur', country_id: 'country-in', state_id: 'state-mh', name: 'Kolhapur', slug: 'kolhapur', is_popular: false, is_active: true, sort_order: 25 },
  { id: 'city-amravati', country_id: 'country-in', state_id: 'state-mh', name: 'Amravati', slug: 'amravati', is_popular: false, is_active: true, sort_order: 26 },

  // --- DELHI NCR & HARYANA & UP ---
  { id: 'city-delhi', country_id: 'country-in', state_id: 'state-dl', name: 'New Delhi', slug: 'new-delhi', is_popular: true, is_active: true, sort_order: 27 },
  { id: 'city-gurugram', country_id: 'country-in', state_id: 'state-hr', name: 'Gurugram', slug: 'gurugram', is_popular: true, is_active: true, sort_order: 28 },
  { id: 'city-faridabad', country_id: 'country-in', state_id: 'state-hr', name: 'Faridabad', slug: 'faridabad', is_popular: false, is_active: true, sort_order: 29 },
  { id: 'city-panipat', country_id: 'country-in', state_id: 'state-hr', name: 'Panipat', slug: 'panipat', is_popular: false, is_active: true, sort_order: 30 },
  { id: 'city-ambala', country_id: 'country-in', state_id: 'state-hr', name: 'Ambala', slug: 'ambala', is_popular: false, is_active: true, sort_order: 31 },
  { id: 'city-karnal', country_id: 'country-in', state_id: 'state-hr', name: 'Karnal', slug: 'karnal', is_popular: false, is_active: true, sort_order: 32 },
  { id: 'city-noida', country_id: 'country-in', state_id: 'state-up', name: 'Noida', slug: 'noida', is_popular: true, is_active: true, sort_order: 33 },
  { id: 'city-gr-noida', country_id: 'country-in', state_id: 'state-up', name: 'Greater Noida', slug: 'greater-noida', is_popular: true, is_active: true, sort_order: 34 },
  { id: 'city-ghaziabad', country_id: 'country-in', state_id: 'state-up', name: 'Ghaziabad', slug: 'ghaziabad', is_popular: false, is_active: true, sort_order: 35 },
  { id: 'city-lucknow', country_id: 'country-in', state_id: 'state-up', name: 'Lucknow', slug: 'lucknow', is_popular: true, is_active: true, sort_order: 36 },
  { id: 'city-kanpur', country_id: 'country-in', state_id: 'state-up', name: 'Kanpur', slug: 'kanpur', is_popular: false, is_active: true, sort_order: 37 },
  { id: 'city-varanasi', country_id: 'country-in', state_id: 'state-up', name: 'Varanasi', slug: 'varanasi', is_popular: false, is_active: true, sort_order: 38 },
  { id: 'city-agra', country_id: 'country-in', state_id: 'state-up', name: 'Agra', slug: 'agra', is_popular: false, is_active: true, sort_order: 39 },
  { id: 'city-prayagraj', country_id: 'country-in', state_id: 'state-up', name: 'Prayagraj', slug: 'prayagraj', is_popular: false, is_active: true, sort_order: 40 },
  { id: 'city-meerut', country_id: 'country-in', state_id: 'state-up', name: 'Meerut', slug: 'meerut', is_popular: false, is_active: true, sort_order: 41 },
  { id: 'city-bareilly', country_id: 'country-in', state_id: 'state-up', name: 'Bareilly', slug: 'bareilly', is_popular: false, is_active: true, sort_order: 42 },
  { id: 'city-aligarh', country_id: 'country-in', state_id: 'state-up', name: 'Aligarh', slug: 'aligarh', is_popular: false, is_active: true, sort_order: 43 },
  { id: 'city-moradabad', country_id: 'country-in', state_id: 'state-up', name: 'Moradabad', slug: 'moradabad', is_popular: false, is_active: true, sort_order: 44 },

  // --- TAMIL NADU ---
  { id: 'city-chennai', country_id: 'country-in', state_id: 'state-tn', name: 'Chennai', slug: 'chennai', is_popular: true, is_active: true, sort_order: 45 },
  { id: 'city-coimbatore', country_id: 'country-in', state_id: 'state-tn', name: 'Coimbatore', slug: 'coimbatore', is_popular: true, is_active: true, sort_order: 46 },
  { id: 'city-madurai', country_id: 'country-in', state_id: 'state-tn', name: 'Madurai', slug: 'madurai', is_popular: false, is_active: true, sort_order: 47 },
  { id: 'city-trichy', country_id: 'country-in', state_id: 'state-tn', name: 'Tiruchirappalli', slug: 'tiruchirappalli', is_popular: false, is_active: true, sort_order: 48 },
  { id: 'city-salem', country_id: 'country-in', state_id: 'state-tn', name: 'Salem', slug: 'salem', is_popular: false, is_active: true, sort_order: 49 },
  { id: 'city-tirunelveli', country_id: 'country-in', state_id: 'state-tn', name: 'Tirunelveli', slug: 'tirunelveli', is_popular: false, is_active: true, sort_order: 50 },
  { id: 'city-tiruppur', country_id: 'country-in', state_id: 'state-tn', name: 'Tiruppur', slug: 'tiruppur', is_popular: false, is_active: true, sort_order: 51 },
  { id: 'city-vellore', country_id: 'country-in', state_id: 'state-tn', name: 'Vellore', slug: 'vellore', is_popular: false, is_active: true, sort_order: 52 },
  { id: 'city-erode', country_id: 'country-in', state_id: 'state-tn', name: 'Erode', slug: 'erode', is_popular: false, is_active: true, sort_order: 53 },

  // --- ANDHRA PRADESH ---
  { id: 'city-vizag', country_id: 'country-in', state_id: 'state-ap', name: 'Visakhapatnam', slug: 'visakhapatnam', is_popular: true, is_active: true, sort_order: 54 },
  { id: 'city-vijayawada', country_id: 'country-in', state_id: 'state-ap', name: 'Vijayawada', slug: 'vijayawada', is_popular: true, is_active: true, sort_order: 55 },
  { id: 'city-guntur', country_id: 'country-in', state_id: 'state-ap', name: 'Guntur', slug: 'guntur', is_popular: false, is_active: true, sort_order: 56 },
  { id: 'city-tirupati', country_id: 'country-in', state_id: 'state-ap', name: 'Tirupati', slug: 'tirupati', is_popular: false, is_active: true, sort_order: 57 },
  { id: 'city-kakinada', country_id: 'country-in', state_id: 'state-ap', name: 'Kakinada', slug: 'kakinada', is_popular: false, is_active: true, sort_order: 58 },
  { id: 'city-nellore', country_id: 'country-in', state_id: 'state-ap', name: 'Nellore', slug: 'nellore', is_popular: false, is_active: true, sort_order: 59 },
  { id: 'city-kurnool', country_id: 'country-in', state_id: 'state-ap', name: 'Kurnool', slug: 'kurnool', is_popular: false, is_active: true, sort_order: 60 },
  { id: 'city-rajahmundry', country_id: 'country-in', state_id: 'state-ap', name: 'Rajahmundry', slug: 'rajahmundry', is_popular: false, is_active: true, sort_order: 61 },
  { id: 'city-anantapur', country_id: 'country-in', state_id: 'state-ap', name: 'Anantapur', slug: 'anantapur', is_popular: false, is_active: true, sort_order: 62 },

  // --- GUJARAT ---
  { id: 'city-ahmedabad', country_id: 'country-in', state_id: 'state-gj', name: 'Ahmedabad', slug: 'ahmedabad', is_popular: true, is_active: true, sort_order: 63 },
  { id: 'city-gandhinagar', country_id: 'country-in', state_id: 'state-gj', name: 'Gandhinagar', slug: 'gandhinagar', is_popular: true, is_active: true, sort_order: 64 },
  { id: 'city-surat', country_id: 'country-in', state_id: 'state-gj', name: 'Surat', slug: 'surat', is_popular: true, is_active: true, sort_order: 65 },
  { id: 'city-vadodara', country_id: 'country-in', state_id: 'state-gj', name: 'Vadodara', slug: 'vadodara', is_popular: true, is_active: true, sort_order: 66 },
  { id: 'city-rajkot', country_id: 'country-in', state_id: 'state-gj', name: 'Rajkot', slug: 'rajkot', is_popular: false, is_active: true, sort_order: 67 },
  { id: 'city-bhavnagar', country_id: 'country-in', state_id: 'state-gj', name: 'Bhavnagar', slug: 'bhavnagar', is_popular: false, is_active: true, sort_order: 68 },
  { id: 'city-jamnagar', country_id: 'country-in', state_id: 'state-gj', name: 'Jamnagar', slug: 'jamnagar', is_popular: false, is_active: true, sort_order: 69 },
  { id: 'city-junagadh', country_id: 'country-in', state_id: 'state-gj', name: 'Junagadh', slug: 'junagadh', is_popular: false, is_active: true, sort_order: 70 },

  // --- KERALA ---
  { id: 'city-kochi', country_id: 'country-in', state_id: 'state-kl', name: 'Kochi', slug: 'kochi', is_popular: true, is_active: true, sort_order: 71 },
  { id: 'city-tvm', country_id: 'country-in', state_id: 'state-kl', name: 'Thiruvananthapuram', slug: 'thiruvananthapuram', is_popular: true, is_active: true, sort_order: 72 },
  { id: 'city-kozhikode', country_id: 'country-in', state_id: 'state-kl', name: 'Kozhikode', slug: 'kozhikode', is_popular: false, is_active: true, sort_order: 73 },
  { id: 'city-thrissur', country_id: 'country-in', state_id: 'state-kl', name: 'Thrissur', slug: 'thrissur', is_popular: false, is_active: true, sort_order: 74 },
  { id: 'city-kollam', country_id: 'country-in', state_id: 'state-kl', name: 'Kollam', slug: 'kollam', is_popular: false, is_active: true, sort_order: 75 },
  { id: 'city-kannur', country_id: 'country-in', state_id: 'state-kl', name: 'Kannur', slug: 'kannur', is_popular: false, is_active: true, sort_order: 76 },
  { id: 'city-alappuzha', country_id: 'country-in', state_id: 'state-kl', name: 'Alappuzha', slug: 'alappuzha', is_popular: false, is_active: true, sort_order: 77 },

  // --- WEST BENGAL ---
  { id: 'city-kolkata', country_id: 'country-in', state_id: 'state-wb', name: 'Kolkata', slug: 'kolkata', is_popular: true, is_active: true, sort_order: 78 },
  { id: 'city-howrah', country_id: 'country-in', state_id: 'state-wb', name: 'Howrah', slug: 'howrah', is_popular: false, is_active: true, sort_order: 79 },
  { id: 'city-siliguri', country_id: 'country-in', state_id: 'state-wb', name: 'Siliguri', slug: 'siliguri', is_popular: false, is_active: true, sort_order: 80 },
  { id: 'city-durgapur', country_id: 'country-in', state_id: 'state-wb', name: 'Durgapur', slug: 'durgapur', is_popular: false, is_active: true, sort_order: 81 },
  { id: 'city-asansol', country_id: 'country-in', state_id: 'state-wb', name: 'Asansol', slug: 'asansol', is_popular: false, is_active: true, sort_order: 82 },

  // --- RAJASTHAN ---
  { id: 'city-jaipur', country_id: 'country-in', state_id: 'state-rj', name: 'Jaipur', slug: 'jaipur', is_popular: true, is_active: true, sort_order: 83 },
  { id: 'city-jodhpur', country_id: 'country-in', state_id: 'state-rj', name: 'Jodhpur', slug: 'jodhpur', is_popular: false, is_active: true, sort_order: 84 },
  { id: 'city-udaipur', country_id: 'country-in', state_id: 'state-rj', name: 'Udaipur', slug: 'udaipur', is_popular: false, is_active: true, sort_order: 85 },
  { id: 'city-kota', country_id: 'country-in', state_id: 'state-rj', name: 'Kota', slug: 'kota', is_popular: false, is_active: true, sort_order: 86 },
  { id: 'city-bikaner', country_id: 'country-in', state_id: 'state-rj', name: 'Bikaner', slug: 'bikaner', is_popular: false, is_active: true, sort_order: 87 },
  { id: 'city-ajmer', country_id: 'country-in', state_id: 'state-rj', name: 'Ajmer', slug: 'ajmer', is_popular: false, is_active: true, sort_order: 88 },

  // --- MADHYA PRADESH ---
  { id: 'city-indore', country_id: 'country-in', state_id: 'state-mp', name: 'Indore', slug: 'indore', is_popular: true, is_active: true, sort_order: 89 },
  { id: 'city-bhopal', country_id: 'country-in', state_id: 'state-mp', name: 'Bhopal', slug: 'bhopal', is_popular: true, is_active: true, sort_order: 90 },
  { id: 'city-jabalpur', country_id: 'country-in', state_id: 'state-mp', name: 'Jabalpur', slug: 'jabalpur', is_popular: false, is_active: true, sort_order: 91 },
  { id: 'city-gwalior', country_id: 'country-in', state_id: 'state-mp', name: 'Gwalior', slug: 'gwalior', is_popular: false, is_active: true, sort_order: 92 },
  { id: 'city-ujjain', country_id: 'country-in', state_id: 'state-mp', name: 'Ujjain', slug: 'ujjain', is_popular: false, is_active: true, sort_order: 93 },

  // --- PUNJAB & CHANDIGARH ---
  { id: 'city-chandigarh', country_id: 'country-in', state_id: 'state-ch', name: 'Chandigarh', slug: 'chandigarh', is_popular: true, is_active: true, sort_order: 94 },
  { id: 'city-mohali', country_id: 'country-in', state_id: 'state-pb', name: 'Mohali', slug: 'mohali', is_popular: true, is_active: true, sort_order: 95 },
  { id: 'city-ludhiana', country_id: 'country-in', state_id: 'state-pb', name: 'Ludhiana', slug: 'ludhiana', is_popular: false, is_active: true, sort_order: 96 },
  { id: 'city-amritsar', country_id: 'country-in', state_id: 'state-pb', name: 'Amritsar', slug: 'amritsar', is_popular: false, is_active: true, sort_order: 97 },
  { id: 'city-jalandhar', country_id: 'country-in', state_id: 'state-pb', name: 'Jalandhar', slug: 'jalandhar', is_popular: false, is_active: true, sort_order: 98 },
  { id: 'city-patiala', country_id: 'country-in', state_id: 'state-pb', name: 'Patiala', slug: 'patiala', is_popular: false, is_active: true, sort_order: 99 },

  // --- ODISHA ---
  { id: 'city-bhubaneswar', country_id: 'country-in', state_id: 'state-od', name: 'Bhubaneswar', slug: 'bhubaneswar', is_popular: true, is_active: true, sort_order: 100 },
  { id: 'city-cuttack', country_id: 'country-in', state_id: 'state-od', name: 'Cuttack', slug: 'cuttack', is_popular: false, is_active: true, sort_order: 101 },
  { id: 'city-rourkela', country_id: 'country-in', state_id: 'state-od', name: 'Rourkela', slug: 'rourkela', is_popular: false, is_active: true, sort_order: 102 },
  { id: 'city-berhampur', country_id: 'country-in', state_id: 'state-od', name: 'Berhampur', slug: 'berhampur', is_popular: false, is_active: true, sort_order: 103 },
  { id: 'city-sambalpur', country_id: 'country-in', state_id: 'state-od', name: 'Sambalpur', slug: 'sambalpur', is_popular: false, is_active: true, sort_order: 104 },

  // --- BIHAR & JHARKHAND ---
  { id: 'city-patna', country_id: 'country-in', state_id: 'state-br', name: 'Patna', slug: 'patna', is_popular: true, is_active: true, sort_order: 105 },
  { id: 'city-gaya', country_id: 'country-in', state_id: 'state-br', name: 'Gaya', slug: 'gaya', is_popular: false, is_active: true, sort_order: 106 },
  { id: 'city-muzaffarpur', country_id: 'country-in', state_id: 'state-br', name: 'Muzaffarpur', slug: 'muzaffarpur', is_popular: false, is_active: true, sort_order: 107 },
  { id: 'city-bhagalpur', country_id: 'country-in', state_id: 'state-br', name: 'Bhagalpur', slug: 'bhagalpur', is_popular: false, is_active: true, sort_order: 108 },
  { id: 'city-ranchi', country_id: 'country-in', state_id: 'state-jh', name: 'Ranchi', slug: 'ranchi', is_popular: true, is_active: true, sort_order: 109 },
  { id: 'city-jamshedpur', country_id: 'country-in', state_id: 'state-jh', name: 'Jamshedpur', slug: 'jamshedpur', is_popular: true, is_active: true, sort_order: 110 },
  { id: 'city-dhanbad', country_id: 'country-in', state_id: 'state-jh', name: 'Dhanbad', slug: 'dhanbad', is_popular: false, is_active: true, sort_order: 111 },
  { id: 'city-bokaro', country_id: 'country-in', state_id: 'state-jh', name: 'Bokaro Steel City', slug: 'bokaro-steel-city', is_popular: false, is_active: true, sort_order: 112 },

  // --- CHHATTISGARH ---
  { id: 'city-raipur', country_id: 'country-in', state_id: 'state-cg', name: 'Raipur', slug: 'raipur', is_popular: true, is_active: true, sort_order: 113 },
  { id: 'city-bhilai', country_id: 'country-in', state_id: 'state-cg', name: 'Bhilai', slug: 'bhilai', is_popular: false, is_active: true, sort_order: 114 },
  { id: 'city-bilaspur', country_id: 'country-in', state_id: 'state-cg', name: 'Bilaspur', slug: 'bilaspur', is_popular: false, is_active: true, sort_order: 115 },
  { id: 'city-korba', country_id: 'country-in', state_id: 'state-cg', name: 'Korba', slug: 'korba', is_popular: false, is_active: true, sort_order: 116 },

  // --- ASSAM & NORTH-EAST ---
  { id: 'city-guwahati', country_id: 'country-in', state_id: 'state-as', name: 'Guwahati', slug: 'guwahati', is_popular: true, is_active: true, sort_order: 117 },
  { id: 'city-silchar', country_id: 'country-in', state_id: 'state-as', name: 'Silchar', slug: 'silchar', is_popular: false, is_active: true, sort_order: 118 },
  { id: 'city-dibrugarh', country_id: 'country-in', state_id: 'state-as', name: 'Dibrugarh', slug: 'dibrugarh', is_popular: false, is_active: true, sort_order: 119 },
  { id: 'city-jorhat', country_id: 'country-in', state_id: 'state-as', name: 'Jorhat', slug: 'jorhat', is_popular: false, is_active: true, sort_order: 120 },
  { id: 'city-shillong', country_id: 'country-in', state_id: 'state-ml', name: 'Shillong', slug: 'shillong', is_popular: false, is_active: true, sort_order: 121 },
  { id: 'city-imphal', country_id: 'country-in', state_id: 'state-mn', name: 'Imphal', slug: 'imphal', is_popular: false, is_active: true, sort_order: 122 },
  { id: 'city-agartala', country_id: 'country-in', state_id: 'state-tr', name: 'Agartala', slug: 'agartala', is_popular: false, is_active: true, sort_order: 123 },
  { id: 'city-aizawl', country_id: 'country-in', state_id: 'state-mz', name: 'Aizawl', slug: 'aizawl', is_popular: false, is_active: true, sort_order: 124 },
  { id: 'city-kohima', country_id: 'country-in', state_id: 'state-nl', name: 'Kohima', slug: 'kohima', is_popular: false, is_active: true, sort_order: 125 },
  { id: 'city-itanagar', country_id: 'country-in', state_id: 'state-ar', name: 'Itanagar', slug: 'itanagar', is_popular: false, is_active: true, sort_order: 126 },
  { id: 'city-gangtok', country_id: 'country-in', state_id: 'state-sk', name: 'Gangtok', slug: 'gangtok', is_popular: false, is_active: true, sort_order: 127 },

  // --- UTTARAKHAND & HIMACHAL PRADESH & J&K ---
  { id: 'city-dehradun', country_id: 'country-in', state_id: 'state-uk', name: 'Dehradun', slug: 'dehradun', is_popular: true, is_active: true, sort_order: 128 },
  { id: 'city-haridwar', country_id: 'country-in', state_id: 'state-uk', name: 'Haridwar', slug: 'haridwar', is_popular: false, is_active: true, sort_order: 129 },
  { id: 'city-roorkee', country_id: 'country-in', state_id: 'state-uk', name: 'Roorkee', slug: 'roorkee', is_popular: false, is_active: true, sort_order: 130 },
  { id: 'city-haldwani', country_id: 'country-in', state_id: 'state-uk', name: 'Haldwani', slug: 'haldwani', is_popular: false, is_active: true, sort_order: 131 },
  { id: 'city-shimla', country_id: 'country-in', state_id: 'state-hp', name: 'Shimla', slug: 'shimla', is_popular: false, is_active: true, sort_order: 132 },
  { id: 'city-dharamshala', country_id: 'country-in', state_id: 'state-hp', name: 'Dharamshala', slug: 'dharamshala', is_popular: false, is_active: true, sort_order: 133 },
  { id: 'city-baddi', country_id: 'country-in', state_id: 'state-hp', name: 'Baddi', slug: 'baddi', is_popular: false, is_active: true, sort_order: 134 },
  { id: 'city-srinagar', country_id: 'country-in', state_id: 'state-jk', name: 'Srinagar', slug: 'srinagar', is_popular: false, is_active: true, sort_order: 135 },
  { id: 'city-jammu', country_id: 'country-in', state_id: 'state-jk', name: 'Jammu', slug: 'jammu', is_popular: false, is_active: true, sort_order: 136 },
  { id: 'city-leh', country_id: 'country-in', state_id: 'state-la', name: 'Leh', slug: 'leh', is_popular: false, is_active: true, sort_order: 137 },

  // --- GOA & UNION TERRITORIES ---
  { id: 'city-panaji', country_id: 'country-in', state_id: 'state-ga', name: 'Panaji', slug: 'panaji', is_popular: true, is_active: true, sort_order: 138 },
  { id: 'city-margao', country_id: 'country-in', state_id: 'state-ga', name: 'Margao', slug: 'margao', is_popular: false, is_active: true, sort_order: 139 },
  { id: 'city-vasco', country_id: 'country-in', state_id: 'state-ga', name: 'Vasco da Gama', slug: 'vasco-da-gama', is_popular: false, is_active: true, sort_order: 140 },
  { id: 'city-puducherry', country_id: 'country-in', state_id: 'state-py', name: 'Puducherry', slug: 'puducherry', is_popular: false, is_active: true, sort_order: 141 },
  { id: 'city-portblair', country_id: 'country-in', state_id: 'state-an', name: 'Port Blair', slug: 'port-blair', is_popular: false, is_active: true, sort_order: 142 },
  { id: 'city-daman', country_id: 'country-in', state_id: 'state-dh', name: 'Daman', slug: 'daman', is_popular: false, is_active: true, sort_order: 143 },
  { id: 'city-diu', country_id: 'country-in', state_id: 'state-dh', name: 'Diu', slug: 'diu', is_popular: false, is_active: true, sort_order: 144 },
  { id: 'city-silvassa', country_id: 'country-in', state_id: 'state-dh', name: 'Silvassa', slug: 'silvassa', is_popular: false, is_active: true, sort_order: 145 },
  { id: 'city-kavaratti', country_id: 'country-in', state_id: 'state-ld', name: 'Kavaratti', slug: 'kavaratti', is_popular: false, is_active: true, sort_order: 146 },

  // --- GLOBAL METROPOLITAN HUBS ---
  { id: 'city-nyc', country_id: 'country-us', name: 'New York', slug: 'new-york', is_popular: true, is_active: true, sort_order: 147 },
  { id: 'city-sf', country_id: 'country-us', name: 'San Francisco', slug: 'san-francisco', is_popular: true, is_active: true, sort_order: 148 },
  { id: 'city-seattle', country_id: 'country-us', name: 'Seattle', slug: 'seattle', is_popular: true, is_active: true, sort_order: 149 },
  { id: 'city-austin', country_id: 'country-us', name: 'Austin', slug: 'austin', is_popular: true, is_active: true, sort_order: 150 },
  { id: 'city-boston', country_id: 'country-us', name: 'Boston', slug: 'boston', is_popular: true, is_active: true, sort_order: 151 },
  { id: 'city-chicago', country_id: 'country-us', name: 'Chicago', slug: 'chicago', is_popular: true, is_active: true, sort_order: 152 },
  { id: 'city-london', country_id: 'country-uk', name: 'London', slug: 'london', is_popular: true, is_active: true, sort_order: 153 },
  { id: 'city-manchester', country_id: 'country-uk', name: 'Manchester', slug: 'manchester', is_popular: false, is_active: true, sort_order: 154 },
  { id: 'city-toronto', country_id: 'country-ca', name: 'Toronto', slug: 'toronto', is_popular: true, is_active: true, sort_order: 155 },
  { id: 'city-vancouver', country_id: 'country-ca', name: 'Vancouver', slug: 'vancouver', is_popular: true, is_active: true, sort_order: 156 },
  { id: 'city-sg', country_id: 'country-sg', name: 'Singapore', slug: 'singapore-city', is_popular: true, is_active: true, sort_order: 157 },
  { id: 'city-dubai', country_id: 'country-ae', name: 'Dubai', slug: 'dubai', is_popular: true, is_active: true, sort_order: 158 },
  { id: 'city-abu-dhabi', country_id: 'country-ae', name: 'Abu Dhabi', slug: 'abu-dhabi', is_popular: true, is_active: true, sort_order: 159 },
  { id: 'city-berlin', country_id: 'country-de', name: 'Berlin', slug: 'berlin', is_popular: true, is_active: true, sort_order: 160 },
  { id: 'city-munich', country_id: 'country-de', name: 'Munich', slug: 'munich', is_popular: true, is_active: true, sort_order: 161 },
  { id: 'city-frankfurt', country_id: 'country-de', name: 'Frankfurt', slug: 'frankfurt', is_popular: true, is_active: true, sort_order: 162 },
  { id: 'city-sydney', country_id: 'country-au', name: 'Sydney', slug: 'sydney', is_popular: true, is_active: true, sort_order: 163 },
  { id: 'city-melbourne', country_id: 'country-au', name: 'Melbourne', slug: 'melbourne', is_popular: true, is_active: true, sort_order: 164 },
  { id: 'city-tokyo', country_id: 'country-jp', name: 'Tokyo', slug: 'tokyo', is_popular: true, is_active: true, sort_order: 165 },
  { id: 'city-riyadh', country_id: 'country-sa', name: 'Riyadh', slug: 'riyadh', is_popular: true, is_active: true, sort_order: 166 },
  { id: 'city-amsterdam', country_id: 'country-nl', name: 'Amsterdam', slug: 'amsterdam', is_popular: true, is_active: true, sort_order: 167 },
  { id: 'city-zurich', country_id: 'country-ch', name: 'Zurich', slug: 'zurich', is_popular: true, is_active: true, sort_order: 168 },
  { id: 'city-geneva', country_id: 'country-ch', name: 'Geneva', slug: 'geneva', is_popular: true, is_active: true, sort_order: 169 },
  { id: 'city-stockholm', country_id: 'country-se', name: 'Stockholm', slug: 'stockholm', is_popular: true, is_active: true, sort_order: 170 },
  { id: 'city-dublin', country_id: 'country-ie', name: 'Dublin', slug: 'dublin', is_popular: true, is_active: true, sort_order: 171 },
  { id: 'city-paris', country_id: 'country-fr', name: 'Paris', slug: 'paris', is_popular: true, is_active: true, sort_order: 172 },
];
