export const ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  PRIVACY: '/privacy',
  TERMS: '/terms',
  COMING_SOON: '/coming-soon',
  LOGIN: '/login',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verify-email',
  JOBS: '/jobs',
  JOB_DETAILS: '/jobs/:id',
  RESOURCES: '/resources',
  RESOURCE_DETAILS: '/resources/:id',
  TEMPLATES: '/templates',
  TEMPLATE_DETAILS: '/templates/:id',
  BLOG: '/blog',
  PRICING: '/pricing',
  PUBLIC_PROFILE: '/profile/:candidateId',
  MARKETPLACE: '/marketplace',
  MARKETPLACE_TEMPLATE: '/marketplace/template/:slug',
  CHECKOUT: '/marketplace/checkout',
  ORDER_SUCCESS: '/marketplace/success',

  DASHBOARD: {
    ROOT: '/dashboard',
    CANDIDATE: {
      ROOT: '/dashboard/candidate',
      PORTFOLIO: '/dashboard/candidate/portfolio',
      EXPERIENCE: '/dashboard/candidate/experience',
      SKILLS: '/dashboard/candidate/skills',
      JOBS: '/dashboard/candidate/jobs',
      SAVED: '/dashboard/candidate/saved',
      EDUCATION: '/dashboard/candidate/education',
      CERTIFICATIONS: '/dashboard/candidate/certifications',
      PROJECTS: '/dashboard/candidate/projects',
      ALERTS: '/dashboard/candidate/alerts',
      NOTIFICATIONS: '/dashboard/candidate/notifications',
      PURCHASES: '/dashboard/candidate/purchases',
      BILLING: '/dashboard/candidate/billing',
      SUBSCRIPTIONS: '/dashboard/candidate/subscriptions',
    },
    EMPLOYER: {
      ROOT: '/dashboard/employer',
      COMPANY: '/dashboard/employer/company',
      LOCATIONS: '/dashboard/employer/locations',
      TEAM: '/dashboard/employer/team',
      JOBS: '/dashboard/employer/jobs',
      CREATE_JOB: '/dashboard/employer/jobs/create',
    },
    ADMIN: {
      ROOT: '/dashboard/admin',
      MODERATION: '/dashboard/admin/moderation',
      USERS: '/dashboard/admin/users',
      CANDIDATES: '/dashboard/admin/candidates',
      EMPLOYERS: '/dashboard/admin/employers',
      APPLICATIONS: '/dashboard/admin/applications',
      RESOURCES: '/dashboard/admin/resources',
      TEMPLATES: '/dashboard/admin/templates',
      BLOG: '/dashboard/admin/blog',
      ORDERS: '/dashboard/admin/orders',
      SUBSCRIPTIONS: '/dashboard/admin/subscriptions',
      AI: '/dashboard/admin/ai',
      ANALYTICS: '/dashboard/admin/analytics',
      AUDIT_LOGS: '/dashboard/admin/audit-logs',
      ROLES: '/dashboard/admin/roles',
      SETTINGS: '/dashboard/admin/settings',
    }
  }
} as const;
